### ISSUE TITLE
Same `domain` as in core AccuWeather integration

### ISSUE THREAD

**Issue by bieniu** [rotgier/home-assistant-accuweather#2]
I recommend that the custom integration uses a different domain than the core integration. The same domain for two integrations that use different configuration schemes can cause a lot of problems for users.

Maybe
```python
DOMAIN = "accuweather_custom"
```

https://github.com/rotgier/home-assistant-accuweather/blob/c82b2380b8afcd7455b9c92f069c8dc8cbb714df/custom_components/accuweather/const.py#L33

**Comment by rotgier** [comment]
Sure, will change this.

If you have some less important comments than you can add them directly in the PR: https://github.com/rotgier/home-assistant-accuweather/pull/1/files#
